


include_directories(${CMAKE_CURRENT_SOURCE_DIR})

add_library(e4c-kdm-code SHARED
	kdm/code/CodePackage.cpp
	kdm/code/AbstractCodeElement.cpp
	kdm/code/CodeItem.cpp
	kdm/code/ComputationalObject.cpp
	kdm/code/ControlElement.cpp
	kdm/code/MethodUnit.cpp
	kdm/code/Module.cpp
	kdm/code/CodeAssembly.cpp
	kdm/code/CallableUnit.cpp
	kdm/code/Datatype.cpp
	kdm/code/TemplateUnit.cpp
	kdm/code/TemplateParameter.cpp
	kdm/code/AbstractCodeRelationship.cpp
	kdm/code/InstanceOf.cpp
	kdm/code/CompilationUnit.cpp
	kdm/code/CodeModel.cpp
	kdm/code/DerivedType.cpp
	kdm/code/ArrayType.cpp
	kdm/code/PrimitiveType.cpp
	kdm/code/BooleanType.cpp
	kdm/code/CharType.cpp
	kdm/code/ClassUnit.cpp
	kdm/code/CompositeType.cpp
	kdm/code/RecordType.cpp
	kdm/code/EnumeratedType.cpp
	kdm/code/Extends.cpp
	kdm/code/ScaledType.cpp
	kdm/code/FloatType.cpp
	kdm/code/HasType.cpp
	kdm/code/ImplementationOf.cpp
	kdm/code/Implements.cpp
	kdm/code/IntegerType.cpp
	kdm/code/InterfaceUnit.cpp
	kdm/code/PointerType.cpp
	kdm/code/DefinedType.cpp
	kdm/code/TypeUnit.cpp
	kdm/code/RangeType.cpp
	kdm/code/Signature.cpp
	kdm/code/DataElement.cpp
	kdm/code/StringType.cpp
	kdm/code/ChoiceType.cpp
	kdm/code/NamespaceUnit.cpp
	kdm/code/VisibleIn.cpp
	kdm/code/CommentUnit.cpp
	kdm/code/SharedUnit.cpp
	kdm/code/DecimalType.cpp
	kdm/code/DateType.cpp
	kdm/code/TimeType.cpp
	kdm/code/VoidType.cpp
	kdm/code/ValueElement.cpp
	kdm/code/Value.cpp
	kdm/code/ValueList.cpp
	kdm/code/StorableUnit.cpp
	kdm/code/MemberUnit.cpp
	kdm/code/ParameterUnit.cpp
	kdm/code/ItemUnit.cpp
	kdm/code/IndexUnit.cpp
	kdm/code/SynonymType.cpp
	kdm/code/SequenceType.cpp
	kdm/code/BagType.cpp
	kdm/code/SetType.cpp
	kdm/code/CodeElement.cpp
	kdm/code/CodeRelationship.cpp
	kdm/code/LanguageUnit.cpp
	kdm/code/OrdinalType.cpp
	kdm/code/BitstringType.cpp
	kdm/code/OctetType.cpp
	kdm/code/OctetstringType.cpp
	kdm/code/BitType.cpp
	kdm/code/Imports.cpp
	kdm/code/Package.cpp
	kdm/code/ParameterTo.cpp
	kdm/code/TemplateType.cpp
	kdm/code/PreprocessorDirective.cpp
	kdm/code/MacroDirective.cpp
	kdm/code/MacroUnit.cpp
	kdm/code/ConditionalDirective.cpp
	kdm/code/IncludeDirective.cpp
	kdm/code/VariantTo.cpp
	kdm/code/Expands.cpp
	kdm/code/Redefines.cpp
	kdm/code/GeneratedFrom.cpp
	kdm/code/Includes.cpp
	kdm/code/HasValue.cpp
	)

