#ifndef EMF_CPP_ECORE_PACKAGE_HPP
#define EMF_CPP_ECORE_PACKAGE_HPP

#include <e4c/tag.hpp>
#include <ecore/EPackage.hpp>
#include <ecore/fwd.hpp>

namespace ecore
{


class EcorePackage : public ::ecore::EPackage
{
public:
    static const EcorePackage_ptr _instance();

 	::ecore::EClass_ptr getEAttribute() const;
 	::ecore::EClass_ptr getEAnnotation() const;
 	::ecore::EClass_ptr getEClass() const;
 	::ecore::EClass_ptr getEClassifier() const;
 	::ecore::EClass_ptr getEDataType() const;
 	::ecore::EClass_ptr getEEnum() const;
 	::ecore::EClass_ptr getEEnumLiteral() const;
 	::ecore::EClass_ptr getEFactory() const;
 	::ecore::EClass_ptr getEModelElement() const;
 	::ecore::EClass_ptr getENamedElement() const;
 	::ecore::EClass_ptr getEObject() const;
 	::ecore::EClass_ptr getEOperation() const;
 	::ecore::EClass_ptr getEPackage() const;
 	::ecore::EClass_ptr getEParameter() const;
 	::ecore::EClass_ptr getEReference() const;
 	::ecore::EClass_ptr getEStructuralFeature() const;
 	::ecore::EClass_ptr getETypedElement() const;
 	::ecore::EDataType_ptr getEBigDecimal() const;
 	::ecore::EDataType_ptr getEBigInteger() const;
 	::ecore::EDataType_ptr getEBoolean() const;
 	::ecore::EDataType_ptr getEBooleanObject() const;
 	::ecore::EDataType_ptr getEByte() const;
 	::ecore::EDataType_ptr getEByteArray() const;
 	::ecore::EDataType_ptr getEByteObject() const;
 	::ecore::EDataType_ptr getEChar() const;
 	::ecore::EDataType_ptr getECharacterObject() const;
 	::ecore::EDataType_ptr getEDate() const;
 	::ecore::EDataType_ptr getEDiagnosticChain() const;
 	::ecore::EDataType_ptr getEDouble() const;
 	::ecore::EDataType_ptr getEDoubleObject() const;
 	::ecore::EDataType_ptr getEEList() const;
 	::ecore::EDataType_ptr getEEnumerator() const;
 	::ecore::EDataType_ptr getEFeatureMap() const;
 	::ecore::EDataType_ptr getEFeatureMapEntry() const;
 	::ecore::EDataType_ptr getEFloat() const;
 	::ecore::EDataType_ptr getEFloatObject() const;
 	::ecore::EDataType_ptr getEInt() const;
 	::ecore::EDataType_ptr getEIntegerObject() const;
 	::ecore::EDataType_ptr getEJavaClass() const;
 	::ecore::EDataType_ptr getEJavaObject() const;
 	::ecore::EDataType_ptr getELong() const;
 	::ecore::EDataType_ptr getELongObject() const;
 	::ecore::EDataType_ptr getEMap() const;
 	::ecore::EDataType_ptr getEResource() const;
 	::ecore::EDataType_ptr getEResourceSet() const;
 	::ecore::EDataType_ptr getEShort() const;
 	::ecore::EDataType_ptr getEShortObject() const;
 	::ecore::EDataType_ptr getEString() const;
 	::ecore::EClass_ptr getEStringToStringMapEntry() const;
 	::ecore::EDataType_ptr getETreeIterator() const;
 	::ecore::EClass_ptr getEGenericType() const;
 	::ecore::EClass_ptr getETypeParameter() const;
 	::ecore::EDataType_ptr getEInvocationTargetException() const;
 
 	e4c::tag_t getTag_EAttribute() const;
 	e4c::tag_t getTag_EAnnotation() const;
 	e4c::tag_t getTag_EClass() const;
 	e4c::tag_t getTag_EClassifier() const;
 	e4c::tag_t getTag_EDataType() const;
 	e4c::tag_t getTag_EEnum() const;
 	e4c::tag_t getTag_EEnumLiteral() const;
 	e4c::tag_t getTag_EFactory() const;
 	e4c::tag_t getTag_EModelElement() const;
 	e4c::tag_t getTag_ENamedElement() const;
 	e4c::tag_t getTag_EObject() const;
 	e4c::tag_t getTag_EOperation() const;
 	e4c::tag_t getTag_EPackage() const;
 	e4c::tag_t getTag_EParameter() const;
 	e4c::tag_t getTag_EReference() const;
 	e4c::tag_t getTag_EStructuralFeature() const;
 	e4c::tag_t getTag_ETypedElement() const;
 	e4c::tag_t getTag_EBigDecimal() const;
 	e4c::tag_t getTag_EBigInteger() const;
 	e4c::tag_t getTag_EBoolean() const;
 	e4c::tag_t getTag_EBooleanObject() const;
 	e4c::tag_t getTag_EByte() const;
 	e4c::tag_t getTag_EByteArray() const;
 	e4c::tag_t getTag_EByteObject() const;
 	e4c::tag_t getTag_EChar() const;
 	e4c::tag_t getTag_ECharacterObject() const;
 	e4c::tag_t getTag_EDate() const;
 	e4c::tag_t getTag_EDiagnosticChain() const;
 	e4c::tag_t getTag_EDouble() const;
 	e4c::tag_t getTag_EDoubleObject() const;
 	e4c::tag_t getTag_EEList() const;
 	e4c::tag_t getTag_EEnumerator() const;
 	e4c::tag_t getTag_EFeatureMap() const;
 	e4c::tag_t getTag_EFeatureMapEntry() const;
 	e4c::tag_t getTag_EFloat() const;
 	e4c::tag_t getTag_EFloatObject() const;
 	e4c::tag_t getTag_EInt() const;
 	e4c::tag_t getTag_EIntegerObject() const;
 	e4c::tag_t getTag_EJavaClass() const;
 	e4c::tag_t getTag_EJavaObject() const;
 	e4c::tag_t getTag_ELong() const;
 	e4c::tag_t getTag_ELongObject() const;
 	e4c::tag_t getTag_EMap() const;
 	e4c::tag_t getTag_EResource() const;
 	e4c::tag_t getTag_EResourceSet() const;
 	e4c::tag_t getTag_EShort() const;
 	e4c::tag_t getTag_EShortObject() const;
 	e4c::tag_t getTag_EString() const;
 	e4c::tag_t getTag_EStringToStringMapEntry() const;
 	e4c::tag_t getTag_ETreeIterator() const;
 	e4c::tag_t getTag_EGenericType() const;
 	e4c::tag_t getTag_ETypeParameter() const;
 	e4c::tag_t getTag_EInvocationTargetException() const;
 
 	e4c::tag_t getTag_EAttribute__iD() const;
 	e4c::tag_t getTag_EAttribute__eAttributeType() const;
 	e4c::tag_t getTag_EAnnotation__source() const;
 	e4c::tag_t getTag_EAnnotation__details() const;
 	e4c::tag_t getTag_EAnnotation__eModelElement() const;
 	e4c::tag_t getTag_EAnnotation__contents() const;
 	e4c::tag_t getTag_EAnnotation__references() const;
 	e4c::tag_t getTag_EClass__abstract() const;
 	e4c::tag_t getTag_EClass__interface() const;
 	e4c::tag_t getTag_EClass__eSuperTypes() const;
 	e4c::tag_t getTag_EClass__eOperations() const;
 	e4c::tag_t getTag_EClass__eAllAttributes() const;
 	e4c::tag_t getTag_EClass__eAllReferences() const;
 	e4c::tag_t getTag_EClass__eReferences() const;
 	e4c::tag_t getTag_EClass__eAttributes() const;
 	e4c::tag_t getTag_EClass__eAllContainments() const;
 	e4c::tag_t getTag_EClass__eAllOperations() const;
 	e4c::tag_t getTag_EClass__eAllStructuralFeatures() const;
 	e4c::tag_t getTag_EClass__eAllSuperTypes() const;
 	e4c::tag_t getTag_EClass__eIDAttribute() const;
 	e4c::tag_t getTag_EClass__eStructuralFeatures() const;
 	e4c::tag_t getTag_EClass__eGenericSuperTypes() const;
 	e4c::tag_t getTag_EClass__eAllGenericSuperTypes() const;
 	e4c::tag_t getTag_EClassifier__instanceClassName() const;
 	e4c::tag_t getTag_EClassifier__instanceClass() const;
 	e4c::tag_t getTag_EClassifier__defaultValue() const;
 	e4c::tag_t getTag_EClassifier__instanceTypeName() const;
 	e4c::tag_t getTag_EClassifier__ePackage() const;
 	e4c::tag_t getTag_EClassifier__eTypeParameters() const;
 	e4c::tag_t getTag_EDataType__serializable() const;
 	e4c::tag_t getTag_EEnum__eLiterals() const;
 	e4c::tag_t getTag_EEnumLiteral__value() const;
 	e4c::tag_t getTag_EEnumLiteral__instance() const;
 	e4c::tag_t getTag_EEnumLiteral__literal() const;
 	e4c::tag_t getTag_EEnumLiteral__eEnum() const;
 	e4c::tag_t getTag_EFactory__ePackage() const;
 	e4c::tag_t getTag_EModelElement__eAnnotations() const;
 	e4c::tag_t getTag_ENamedElement__name() const;
 	e4c::tag_t getTag_EOperation__eContainingClass() const;
 	e4c::tag_t getTag_EOperation__eTypeParameters() const;
 	e4c::tag_t getTag_EOperation__eParameters() const;
 	e4c::tag_t getTag_EOperation__eExceptions() const;
 	e4c::tag_t getTag_EOperation__eGenericExceptions() const;
 	e4c::tag_t getTag_EPackage__nsURI() const;
 	e4c::tag_t getTag_EPackage__nsPrefix() const;
 	e4c::tag_t getTag_EPackage__eFactoryInstance() const;
 	e4c::tag_t getTag_EPackage__eClassifiers() const;
 	e4c::tag_t getTag_EPackage__eSubpackages() const;
 	e4c::tag_t getTag_EPackage__eSuperPackage() const;
 	e4c::tag_t getTag_EParameter__eOperation() const;
 	e4c::tag_t getTag_EReference__containment() const;
 	e4c::tag_t getTag_EReference__container() const;
 	e4c::tag_t getTag_EReference__resolveProxies() const;
 	e4c::tag_t getTag_EReference__eOpposite() const;
 	e4c::tag_t getTag_EReference__eReferenceType() const;
 	e4c::tag_t getTag_EReference__eKeys() const;
 	e4c::tag_t getTag_EStructuralFeature__changeable() const;
 	e4c::tag_t getTag_EStructuralFeature__volatile() const;
 	e4c::tag_t getTag_EStructuralFeature__transient() const;
 	e4c::tag_t getTag_EStructuralFeature__defaultValueLiteral() const;
 	e4c::tag_t getTag_EStructuralFeature__defaultValue() const;
 	e4c::tag_t getTag_EStructuralFeature__unsettable() const;
 	e4c::tag_t getTag_EStructuralFeature__derived() const;
 	e4c::tag_t getTag_EStructuralFeature__eContainingClass() const;
 	e4c::tag_t getTag_ETypedElement__ordered() const;
 	e4c::tag_t getTag_ETypedElement__unique() const;
 	e4c::tag_t getTag_ETypedElement__lowerBound() const;
 	e4c::tag_t getTag_ETypedElement__upperBound() const;
 	e4c::tag_t getTag_ETypedElement__many() const;
 	e4c::tag_t getTag_ETypedElement__required() const;
 	e4c::tag_t getTag_ETypedElement__eType() const;
 	e4c::tag_t getTag_ETypedElement__eGenericType() const;
 	e4c::tag_t getTag_EStringToStringMapEntry__key() const;
 	e4c::tag_t getTag_EStringToStringMapEntry__value() const;
 	e4c::tag_t getTag_EGenericType__eUpperBound() const;
 	e4c::tag_t getTag_EGenericType__eTypeArguments() const;
 	e4c::tag_t getTag_EGenericType__eRawType() const;
 	e4c::tag_t getTag_EGenericType__eLowerBound() const;
 	e4c::tag_t getTag_EGenericType__eTypeParameter() const;
 	e4c::tag_t getTag_EGenericType__eClassifier() const;
 	e4c::tag_t getTag_ETypeParameter__eBounds() const;

protected:
    EcorePackage();
    
 	::ecore::EClass_ptr m_EAttribute;
 	::ecore::EClass_ptr m_EAnnotation;
 	::ecore::EClass_ptr m_EClass;
 	::ecore::EClass_ptr m_EClassifier;
 	::ecore::EClass_ptr m_EDataType;
 	::ecore::EClass_ptr m_EEnum;
 	::ecore::EClass_ptr m_EEnumLiteral;
 	::ecore::EClass_ptr m_EFactory;
 	::ecore::EClass_ptr m_EModelElement;
 	::ecore::EClass_ptr m_ENamedElement;
 	::ecore::EClass_ptr m_EObject;
 	::ecore::EClass_ptr m_EOperation;
 	::ecore::EClass_ptr m_EPackage;
 	::ecore::EClass_ptr m_EParameter;
 	::ecore::EClass_ptr m_EReference;
 	::ecore::EClass_ptr m_EStructuralFeature;
 	::ecore::EClass_ptr m_ETypedElement;
 	::ecore::EDataType_ptr m_EBigDecimal;
 	::ecore::EDataType_ptr m_EBigInteger;
 	::ecore::EDataType_ptr m_EBoolean;
 	::ecore::EDataType_ptr m_EBooleanObject;
 	::ecore::EDataType_ptr m_EByte;
 	::ecore::EDataType_ptr m_EByteArray;
 	::ecore::EDataType_ptr m_EByteObject;
 	::ecore::EDataType_ptr m_EChar;
 	::ecore::EDataType_ptr m_ECharacterObject;
 	::ecore::EDataType_ptr m_EDate;
 	::ecore::EDataType_ptr m_EDiagnosticChain;
 	::ecore::EDataType_ptr m_EDouble;
 	::ecore::EDataType_ptr m_EDoubleObject;
 	::ecore::EDataType_ptr m_EEList;
 	::ecore::EDataType_ptr m_EEnumerator;
 	::ecore::EDataType_ptr m_EFeatureMap;
 	::ecore::EDataType_ptr m_EFeatureMapEntry;
 	::ecore::EDataType_ptr m_EFloat;
 	::ecore::EDataType_ptr m_EFloatObject;
 	::ecore::EDataType_ptr m_EInt;
 	::ecore::EDataType_ptr m_EIntegerObject;
 	::ecore::EDataType_ptr m_EJavaClass;
 	::ecore::EDataType_ptr m_EJavaObject;
 	::ecore::EDataType_ptr m_ELong;
 	::ecore::EDataType_ptr m_ELongObject;
 	::ecore::EDataType_ptr m_EMap;
 	::ecore::EDataType_ptr m_EResource;
 	::ecore::EDataType_ptr m_EResourceSet;
 	::ecore::EDataType_ptr m_EShort;
 	::ecore::EDataType_ptr m_EShortObject;
 	::ecore::EDataType_ptr m_EString;
 	::ecore::EClass_ptr m_EStringToStringMapEntry;
 	::ecore::EDataType_ptr m_ETreeIterator;
 	::ecore::EClass_ptr m_EGenericType;
 	::ecore::EClass_ptr m_ETypeParameter;
 	::ecore::EDataType_ptr m_EInvocationTargetException;
};

} // ecore


#endif // EMF_CPP_ECORE_PACKAGE_HPP
