#ifndef EMF_CPP_ECORE_PACKAGE_HPP
#define EMF_CPP_ECORE_PACKAGE_HPP

#include <e4c/tag.hpp>
#include <ecore/EPackage.hpp>
#include <ecore/fwd.hpp>

namespace ecore
{


class EcorePackage : public ::ecore::EPackage
{
public:
    static const EcorePackage_ptr _instance();

 	::ecore::EClass_ptr getEAttribute() const;
 	::ecore::EClass_ptr getEAnnotation() const;
 	::ecore::EClass_ptr getEClass() const;
 	::ecore::EClass_ptr getEClassifier() const;
 	::ecore::EClass_ptr getEDataType() const;
 	::ecore::EClass_ptr getEEnum() const;
 	::ecore::EClass_ptr getEEnumLiteral() const;
 	::ecore::EClass_ptr getEFactory() const;
 	::ecore::EClass_ptr getEModelElement() const;
 	::ecore::EClass_ptr getENamedElement() const;
 	::ecore::EClass_ptr getEObject() const;
 	::ecore::EClass_ptr getEOperation() const;
 	::ecore::EClass_ptr getEPackage() const;
 	::ecore::EClass_ptr getEParameter() const;
 	::ecore::EClass_ptr getEReference() const;
 	::ecore::EClass_ptr getEStructuralFeature() const;
 	::ecore::EClass_ptr getETypedElement() const;
 	::ecore::EDataType_ptr getEBigDecimal() const;
 	::ecore::EDataType_ptr getEBigInteger() const;
 	::ecore::EDataType_ptr getEBoolean() const;
 	::ecore::EDataType_ptr getEBooleanObject() const;
 	::ecore::EDataType_ptr getEByte() const;
 	::ecore::EDataType_ptr getEByteArray() const;
 	::ecore::EDataType_ptr getEByteObject() const;
 	::ecore::EDataType_ptr getEChar() const;
 	::ecore::EDataType_ptr getECharacterObject() const;
 	::ecore::EDataType_ptr getEDate() const;
 	::ecore::EDataType_ptr getEDiagnosticChain() const;
 	::ecore::EDataType_ptr getEDouble() const;
 	::ecore::EDataType_ptr getEDoubleObject() const;
 	::ecore::EDataType_ptr getEEList() const;
 	::ecore::EDataType_ptr getEEnumerator() const;
 	::ecore::EDataType_ptr getEFeatureMap() const;
 	::ecore::EDataType_ptr getEFeatureMapEntry() const;
 	::ecore::EDataType_ptr getEFloat() const;
 	::ecore::EDataType_ptr getEFloatObject() const;
 	::ecore::EDataType_ptr getEInt() const;
 	::ecore::EDataType_ptr getEIntegerObject() const;
 	::ecore::EDataType_ptr getEJavaClass() const;
 	::ecore::EDataType_ptr getEJavaObject() const;
 	::ecore::EDataType_ptr getELong() const;
 	::ecore::EDataType_ptr getELongObject() const;
 	::ecore::EDataType_ptr getEMap() const;
 	::ecore::EDataType_ptr getEResource() const;
 	::ecore::EDataType_ptr getEResourceSet() const;
 	::ecore::EDataType_ptr getEShort() const;
 	::ecore::EDataType_ptr getEShortObject() const;
 	::ecore::EDataType_ptr getEString() const;
 	::ecore::EClass_ptr getEStringToStringMapEntry() const;
 	::ecore::EDataType_ptr getETreeIterator() const;
 	::ecore::EClass_ptr getEGenericType() const;
 	::ecore::EClass_ptr getETypeParameter() const;
 	::ecore::EDataType_ptr getEInvocationTargetException() const;
 	
 	::ecore::EAttribute_ptr getEAttribute__iD() const;
 	::ecore::EReference_ptr getEAttribute__eAttributeType() const;
 	::ecore::EAttribute_ptr getEAnnotation__source() const;
 	::ecore::EReference_ptr getEAnnotation__details() const;
 	::ecore::EReference_ptr getEAnnotation__eModelElement() const;
 	::ecore::EReference_ptr getEAnnotation__contents() const;
 	::ecore::EReference_ptr getEAnnotation__references() const;
 	::ecore::EAttribute_ptr getEClass__abstract() const;
 	::ecore::EAttribute_ptr getEClass__interface() const;
 	::ecore::EReference_ptr getEClass__eSuperTypes() const;
 	::ecore::EReference_ptr getEClass__eOperations() const;
 	::ecore::EReference_ptr getEClass__eAllAttributes() const;
 	::ecore::EReference_ptr getEClass__eAllReferences() const;
 	::ecore::EReference_ptr getEClass__eReferences() const;
 	::ecore::EReference_ptr getEClass__eAttributes() const;
 	::ecore::EReference_ptr getEClass__eAllContainments() const;
 	::ecore::EReference_ptr getEClass__eAllOperations() const;
 	::ecore::EReference_ptr getEClass__eAllStructuralFeatures() const;
 	::ecore::EReference_ptr getEClass__eAllSuperTypes() const;
 	::ecore::EReference_ptr getEClass__eIDAttribute() const;
 	::ecore::EReference_ptr getEClass__eStructuralFeatures() const;
 	::ecore::EReference_ptr getEClass__eGenericSuperTypes() const;
 	::ecore::EReference_ptr getEClass__eAllGenericSuperTypes() const;
 	::ecore::EAttribute_ptr getEClassifier__instanceClassName() const;
 	::ecore::EAttribute_ptr getEClassifier__instanceClass() const;
 	::ecore::EAttribute_ptr getEClassifier__defaultValue() const;
 	::ecore::EAttribute_ptr getEClassifier__instanceTypeName() const;
 	::ecore::EReference_ptr getEClassifier__ePackage() const;
 	::ecore::EReference_ptr getEClassifier__eTypeParameters() const;
 	::ecore::EAttribute_ptr getEDataType__serializable() const;
 	::ecore::EReference_ptr getEEnum__eLiterals() const;
 	::ecore::EAttribute_ptr getEEnumLiteral__value() const;
 	::ecore::EAttribute_ptr getEEnumLiteral__instance() const;
 	::ecore::EAttribute_ptr getEEnumLiteral__literal() const;
 	::ecore::EReference_ptr getEEnumLiteral__eEnum() const;
 	::ecore::EReference_ptr getEFactory__ePackage() const;
 	::ecore::EReference_ptr getEModelElement__eAnnotations() const;
 	::ecore::EAttribute_ptr getENamedElement__name() const;
 	::ecore::EReference_ptr getEOperation__eContainingClass() const;
 	::ecore::EReference_ptr getEOperation__eTypeParameters() const;
 	::ecore::EReference_ptr getEOperation__eParameters() const;
 	::ecore::EReference_ptr getEOperation__eExceptions() const;
 	::ecore::EReference_ptr getEOperation__eGenericExceptions() const;
 	::ecore::EAttribute_ptr getEPackage__nsURI() const;
 	::ecore::EAttribute_ptr getEPackage__nsPrefix() const;
 	::ecore::EReference_ptr getEPackage__eFactoryInstance() const;
 	::ecore::EReference_ptr getEPackage__eClassifiers() const;
 	::ecore::EReference_ptr getEPackage__eSubpackages() const;
 	::ecore::EReference_ptr getEPackage__eSuperPackage() const;
 	::ecore::EReference_ptr getEParameter__eOperation() const;
 	::ecore::EAttribute_ptr getEReference__containment() const;
 	::ecore::EAttribute_ptr getEReference__container() const;
 	::ecore::EAttribute_ptr getEReference__resolveProxies() const;
 	::ecore::EReference_ptr getEReference__eOpposite() const;
 	::ecore::EReference_ptr getEReference__eReferenceType() const;
 	::ecore::EReference_ptr getEReference__eKeys() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__changeable() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__volatile() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__transient() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__defaultValueLiteral() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__defaultValue() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__unsettable() const;
 	::ecore::EAttribute_ptr getEStructuralFeature__derived() const;
 	::ecore::EReference_ptr getEStructuralFeature__eContainingClass() const;
 	::ecore::EAttribute_ptr getETypedElement__ordered() const;
 	::ecore::EAttribute_ptr getETypedElement__unique() const;
 	::ecore::EAttribute_ptr getETypedElement__lowerBound() const;
 	::ecore::EAttribute_ptr getETypedElement__upperBound() const;
 	::ecore::EAttribute_ptr getETypedElement__many() const;
 	::ecore::EAttribute_ptr getETypedElement__required() const;
 	::ecore::EReference_ptr getETypedElement__eType() const;
 	::ecore::EReference_ptr getETypedElement__eGenericType() const;
 	::ecore::EAttribute_ptr getEStringToStringMapEntry__key() const;
 	::ecore::EAttribute_ptr getEStringToStringMapEntry__value() const;
 	::ecore::EReference_ptr getEGenericType__eUpperBound() const;
 	::ecore::EReference_ptr getEGenericType__eTypeArguments() const;
 	::ecore::EReference_ptr getEGenericType__eRawType() const;
 	::ecore::EReference_ptr getEGenericType__eLowerBound() const;
 	::ecore::EReference_ptr getEGenericType__eTypeParameter() const;
 	::ecore::EReference_ptr getEGenericType__eClassifier() const;
 	::ecore::EReference_ptr getETypeParameter__eBounds() const;

 	e4c::tag_t getTag_EAttribute() const;
 	e4c::tag_t getTag_EAnnotation() const;
 	e4c::tag_t getTag_EClass() const;
 	e4c::tag_t getTag_EClassifier() const;
 	e4c::tag_t getTag_EDataType() const;
 	e4c::tag_t getTag_EEnum() const;
 	e4c::tag_t getTag_EEnumLiteral() const;
 	e4c::tag_t getTag_EFactory() const;
 	e4c::tag_t getTag_EModelElement() const;
 	e4c::tag_t getTag_ENamedElement() const;
 	e4c::tag_t getTag_EObject() const;
 	e4c::tag_t getTag_EOperation() const;
 	e4c::tag_t getTag_EPackage() const;
 	e4c::tag_t getTag_EParameter() const;
 	e4c::tag_t getTag_EReference() const;
 	e4c::tag_t getTag_EStructuralFeature() const;
 	e4c::tag_t getTag_ETypedElement() const;
 	e4c::tag_t getTag_EBigDecimal() const;
 	e4c::tag_t getTag_EBigInteger() const;
 	e4c::tag_t getTag_EBoolean() const;
 	e4c::tag_t getTag_EBooleanObject() const;
 	e4c::tag_t getTag_EByte() const;
 	e4c::tag_t getTag_EByteArray() const;
 	e4c::tag_t getTag_EByteObject() const;
 	e4c::tag_t getTag_EChar() const;
 	e4c::tag_t getTag_ECharacterObject() const;
 	e4c::tag_t getTag_EDate() const;
 	e4c::tag_t getTag_EDiagnosticChain() const;
 	e4c::tag_t getTag_EDouble() const;
 	e4c::tag_t getTag_EDoubleObject() const;
 	e4c::tag_t getTag_EEList() const;
 	e4c::tag_t getTag_EEnumerator() const;
 	e4c::tag_t getTag_EFeatureMap() const;
 	e4c::tag_t getTag_EFeatureMapEntry() const;
 	e4c::tag_t getTag_EFloat() const;
 	e4c::tag_t getTag_EFloatObject() const;
 	e4c::tag_t getTag_EInt() const;
 	e4c::tag_t getTag_EIntegerObject() const;
 	e4c::tag_t getTag_EJavaClass() const;
 	e4c::tag_t getTag_EJavaObject() const;
 	e4c::tag_t getTag_ELong() const;
 	e4c::tag_t getTag_ELongObject() const;
 	e4c::tag_t getTag_EMap() const;
 	e4c::tag_t getTag_EResource() const;
 	e4c::tag_t getTag_EResourceSet() const;
 	e4c::tag_t getTag_EShort() const;
 	e4c::tag_t getTag_EShortObject() const;
 	e4c::tag_t getTag_EString() const;
 	e4c::tag_t getTag_EStringToStringMapEntry() const;
 	e4c::tag_t getTag_ETreeIterator() const;
 	e4c::tag_t getTag_EGenericType() const;
 	e4c::tag_t getTag_ETypeParameter() const;
 	e4c::tag_t getTag_EInvocationTargetException() const;
 
 	e4c::tag_t getTag_EAttribute__iD() const;
 	e4c::tag_t getTag_EAttribute__eAttributeType() const;
 	e4c::tag_t getTag_EAnnotation__source() const;
 	e4c::tag_t getTag_EAnnotation__details() const;
 	e4c::tag_t getTag_EAnnotation__eModelElement() const;
 	e4c::tag_t getTag_EAnnotation__contents() const;
 	e4c::tag_t getTag_EAnnotation__references() const;
 	e4c::tag_t getTag_EClass__abstract() const;
 	e4c::tag_t getTag_EClass__interface() const;
 	e4c::tag_t getTag_EClass__eSuperTypes() const;
 	e4c::tag_t getTag_EClass__eOperations() const;
 	e4c::tag_t getTag_EClass__eAllAttributes() const;
 	e4c::tag_t getTag_EClass__eAllReferences() const;
 	e4c::tag_t getTag_EClass__eReferences() const;
 	e4c::tag_t getTag_EClass__eAttributes() const;
 	e4c::tag_t getTag_EClass__eAllContainments() const;
 	e4c::tag_t getTag_EClass__eAllOperations() const;
 	e4c::tag_t getTag_EClass__eAllStructuralFeatures() const;
 	e4c::tag_t getTag_EClass__eAllSuperTypes() const;
 	e4c::tag_t getTag_EClass__eIDAttribute() const;
 	e4c::tag_t getTag_EClass__eStructuralFeatures() const;
 	e4c::tag_t getTag_EClass__eGenericSuperTypes() const;
 	e4c::tag_t getTag_EClass__eAllGenericSuperTypes() const;
 	e4c::tag_t getTag_EClassifier__instanceClassName() const;
 	e4c::tag_t getTag_EClassifier__instanceClass() const;
 	e4c::tag_t getTag_EClassifier__defaultValue() const;
 	e4c::tag_t getTag_EClassifier__instanceTypeName() const;
 	e4c::tag_t getTag_EClassifier__ePackage() const;
 	e4c::tag_t getTag_EClassifier__eTypeParameters() const;
 	e4c::tag_t getTag_EDataType__serializable() const;
 	e4c::tag_t getTag_EEnum__eLiterals() const;
 	e4c::tag_t getTag_EEnumLiteral__value() const;
 	e4c::tag_t getTag_EEnumLiteral__instance() const;
 	e4c::tag_t getTag_EEnumLiteral__literal() const;
 	e4c::tag_t getTag_EEnumLiteral__eEnum() const;
 	e4c::tag_t getTag_EFactory__ePackage() const;
 	e4c::tag_t getTag_EModelElement__eAnnotations() const;
 	e4c::tag_t getTag_ENamedElement__name() const;
 	e4c::tag_t getTag_EOperation__eContainingClass() const;
 	e4c::tag_t getTag_EOperation__eTypeParameters() const;
 	e4c::tag_t getTag_EOperation__eParameters() const;
 	e4c::tag_t getTag_EOperation__eExceptions() const;
 	e4c::tag_t getTag_EOperation__eGenericExceptions() const;
 	e4c::tag_t getTag_EPackage__nsURI() const;
 	e4c::tag_t getTag_EPackage__nsPrefix() const;
 	e4c::tag_t getTag_EPackage__eFactoryInstance() const;
 	e4c::tag_t getTag_EPackage__eClassifiers() const;
 	e4c::tag_t getTag_EPackage__eSubpackages() const;
 	e4c::tag_t getTag_EPackage__eSuperPackage() const;
 	e4c::tag_t getTag_EParameter__eOperation() const;
 	e4c::tag_t getTag_EReference__containment() const;
 	e4c::tag_t getTag_EReference__container() const;
 	e4c::tag_t getTag_EReference__resolveProxies() const;
 	e4c::tag_t getTag_EReference__eOpposite() const;
 	e4c::tag_t getTag_EReference__eReferenceType() const;
 	e4c::tag_t getTag_EReference__eKeys() const;
 	e4c::tag_t getTag_EStructuralFeature__changeable() const;
 	e4c::tag_t getTag_EStructuralFeature__volatile() const;
 	e4c::tag_t getTag_EStructuralFeature__transient() const;
 	e4c::tag_t getTag_EStructuralFeature__defaultValueLiteral() const;
 	e4c::tag_t getTag_EStructuralFeature__defaultValue() const;
 	e4c::tag_t getTag_EStructuralFeature__unsettable() const;
 	e4c::tag_t getTag_EStructuralFeature__derived() const;
 	e4c::tag_t getTag_EStructuralFeature__eContainingClass() const;
 	e4c::tag_t getTag_ETypedElement__ordered() const;
 	e4c::tag_t getTag_ETypedElement__unique() const;
 	e4c::tag_t getTag_ETypedElement__lowerBound() const;
 	e4c::tag_t getTag_ETypedElement__upperBound() const;
 	e4c::tag_t getTag_ETypedElement__many() const;
 	e4c::tag_t getTag_ETypedElement__required() const;
 	e4c::tag_t getTag_ETypedElement__eType() const;
 	e4c::tag_t getTag_ETypedElement__eGenericType() const;
 	e4c::tag_t getTag_EStringToStringMapEntry__key() const;
 	e4c::tag_t getTag_EStringToStringMapEntry__value() const;
 	e4c::tag_t getTag_EGenericType__eUpperBound() const;
 	e4c::tag_t getTag_EGenericType__eTypeArguments() const;
 	e4c::tag_t getTag_EGenericType__eRawType() const;
 	e4c::tag_t getTag_EGenericType__eLowerBound() const;
 	e4c::tag_t getTag_EGenericType__eTypeParameter() const;
 	e4c::tag_t getTag_EGenericType__eClassifier() const;
 	e4c::tag_t getTag_ETypeParameter__eBounds() const;

protected:
    EcorePackage();
    
 	::ecore::EClass_ptr m_EAttribute;
 	::ecore::EClass_ptr m_EAnnotation;
 	::ecore::EClass_ptr m_EClass;
 	::ecore::EClass_ptr m_EClassifier;
 	::ecore::EClass_ptr m_EDataType;
 	::ecore::EClass_ptr m_EEnum;
 	::ecore::EClass_ptr m_EEnumLiteral;
 	::ecore::EClass_ptr m_EFactory;
 	::ecore::EClass_ptr m_EModelElement;
 	::ecore::EClass_ptr m_ENamedElement;
 	::ecore::EClass_ptr m_EObject;
 	::ecore::EClass_ptr m_EOperation;
 	::ecore::EClass_ptr m_EPackage;
 	::ecore::EClass_ptr m_EParameter;
 	::ecore::EClass_ptr m_EReference;
 	::ecore::EClass_ptr m_EStructuralFeature;
 	::ecore::EClass_ptr m_ETypedElement;
 	::ecore::EDataType_ptr m_EBigDecimal;
 	::ecore::EDataType_ptr m_EBigInteger;
 	::ecore::EDataType_ptr m_EBoolean;
 	::ecore::EDataType_ptr m_EBooleanObject;
 	::ecore::EDataType_ptr m_EByte;
 	::ecore::EDataType_ptr m_EByteArray;
 	::ecore::EDataType_ptr m_EByteObject;
 	::ecore::EDataType_ptr m_EChar;
 	::ecore::EDataType_ptr m_ECharacterObject;
 	::ecore::EDataType_ptr m_EDate;
 	::ecore::EDataType_ptr m_EDiagnosticChain;
 	::ecore::EDataType_ptr m_EDouble;
 	::ecore::EDataType_ptr m_EDoubleObject;
 	::ecore::EDataType_ptr m_EEList;
 	::ecore::EDataType_ptr m_EEnumerator;
 	::ecore::EDataType_ptr m_EFeatureMap;
 	::ecore::EDataType_ptr m_EFeatureMapEntry;
 	::ecore::EDataType_ptr m_EFloat;
 	::ecore::EDataType_ptr m_EFloatObject;
 	::ecore::EDataType_ptr m_EInt;
 	::ecore::EDataType_ptr m_EIntegerObject;
 	::ecore::EDataType_ptr m_EJavaClass;
 	::ecore::EDataType_ptr m_EJavaObject;
 	::ecore::EDataType_ptr m_ELong;
 	::ecore::EDataType_ptr m_ELongObject;
 	::ecore::EDataType_ptr m_EMap;
 	::ecore::EDataType_ptr m_EResource;
 	::ecore::EDataType_ptr m_EResourceSet;
 	::ecore::EDataType_ptr m_EShort;
 	::ecore::EDataType_ptr m_EShortObject;
 	::ecore::EDataType_ptr m_EString;
 	::ecore::EClass_ptr m_EStringToStringMapEntry;
 	::ecore::EDataType_ptr m_ETreeIterator;
 	::ecore::EClass_ptr m_EGenericType;
 	::ecore::EClass_ptr m_ETypeParameter;
 	::ecore::EDataType_ptr m_EInvocationTargetException;
 	::ecore::EAttribute_ptr m_EAttribute__iD;
 	::ecore::EReference_ptr m_EAttribute__eAttributeType;
 	::ecore::EAttribute_ptr m_EAnnotation__source;
 	::ecore::EReference_ptr m_EAnnotation__details;
 	::ecore::EReference_ptr m_EAnnotation__eModelElement;
 	::ecore::EReference_ptr m_EAnnotation__contents;
 	::ecore::EReference_ptr m_EAnnotation__references;
 	::ecore::EAttribute_ptr m_EClass__abstract;
 	::ecore::EAttribute_ptr m_EClass__interface;
 	::ecore::EReference_ptr m_EClass__eSuperTypes;
 	::ecore::EReference_ptr m_EClass__eOperations;
 	::ecore::EReference_ptr m_EClass__eAllAttributes;
 	::ecore::EReference_ptr m_EClass__eAllReferences;
 	::ecore::EReference_ptr m_EClass__eReferences;
 	::ecore::EReference_ptr m_EClass__eAttributes;
 	::ecore::EReference_ptr m_EClass__eAllContainments;
 	::ecore::EReference_ptr m_EClass__eAllOperations;
 	::ecore::EReference_ptr m_EClass__eAllStructuralFeatures;
 	::ecore::EReference_ptr m_EClass__eAllSuperTypes;
 	::ecore::EReference_ptr m_EClass__eIDAttribute;
 	::ecore::EReference_ptr m_EClass__eStructuralFeatures;
 	::ecore::EReference_ptr m_EClass__eGenericSuperTypes;
 	::ecore::EReference_ptr m_EClass__eAllGenericSuperTypes;
 	::ecore::EAttribute_ptr m_EClassifier__instanceClassName;
 	::ecore::EAttribute_ptr m_EClassifier__instanceClass;
 	::ecore::EAttribute_ptr m_EClassifier__defaultValue;
 	::ecore::EAttribute_ptr m_EClassifier__instanceTypeName;
 	::ecore::EReference_ptr m_EClassifier__ePackage;
 	::ecore::EReference_ptr m_EClassifier__eTypeParameters;
 	::ecore::EAttribute_ptr m_EDataType__serializable;
 	::ecore::EReference_ptr m_EEnum__eLiterals;
 	::ecore::EAttribute_ptr m_EEnumLiteral__value;
 	::ecore::EAttribute_ptr m_EEnumLiteral__instance;
 	::ecore::EAttribute_ptr m_EEnumLiteral__literal;
 	::ecore::EReference_ptr m_EEnumLiteral__eEnum;
 	::ecore::EReference_ptr m_EFactory__ePackage;
 	::ecore::EReference_ptr m_EModelElement__eAnnotations;
 	::ecore::EAttribute_ptr m_ENamedElement__name;
 	::ecore::EReference_ptr m_EOperation__eContainingClass;
 	::ecore::EReference_ptr m_EOperation__eTypeParameters;
 	::ecore::EReference_ptr m_EOperation__eParameters;
 	::ecore::EReference_ptr m_EOperation__eExceptions;
 	::ecore::EReference_ptr m_EOperation__eGenericExceptions;
 	::ecore::EAttribute_ptr m_EPackage__nsURI;
 	::ecore::EAttribute_ptr m_EPackage__nsPrefix;
 	::ecore::EReference_ptr m_EPackage__eFactoryInstance;
 	::ecore::EReference_ptr m_EPackage__eClassifiers;
 	::ecore::EReference_ptr m_EPackage__eSubpackages;
 	::ecore::EReference_ptr m_EPackage__eSuperPackage;
 	::ecore::EReference_ptr m_EParameter__eOperation;
 	::ecore::EAttribute_ptr m_EReference__containment;
 	::ecore::EAttribute_ptr m_EReference__container;
 	::ecore::EAttribute_ptr m_EReference__resolveProxies;
 	::ecore::EReference_ptr m_EReference__eOpposite;
 	::ecore::EReference_ptr m_EReference__eReferenceType;
 	::ecore::EReference_ptr m_EReference__eKeys;
 	::ecore::EAttribute_ptr m_EStructuralFeature__changeable;
 	::ecore::EAttribute_ptr m_EStructuralFeature__volatile;
 	::ecore::EAttribute_ptr m_EStructuralFeature__transient;
 	::ecore::EAttribute_ptr m_EStructuralFeature__defaultValueLiteral;
 	::ecore::EAttribute_ptr m_EStructuralFeature__defaultValue;
 	::ecore::EAttribute_ptr m_EStructuralFeature__unsettable;
 	::ecore::EAttribute_ptr m_EStructuralFeature__derived;
 	::ecore::EReference_ptr m_EStructuralFeature__eContainingClass;
 	::ecore::EAttribute_ptr m_ETypedElement__ordered;
 	::ecore::EAttribute_ptr m_ETypedElement__unique;
 	::ecore::EAttribute_ptr m_ETypedElement__lowerBound;
 	::ecore::EAttribute_ptr m_ETypedElement__upperBound;
 	::ecore::EAttribute_ptr m_ETypedElement__many;
 	::ecore::EAttribute_ptr m_ETypedElement__required;
 	::ecore::EReference_ptr m_ETypedElement__eType;
 	::ecore::EReference_ptr m_ETypedElement__eGenericType;
 	::ecore::EAttribute_ptr m_EStringToStringMapEntry__key;
 	::ecore::EAttribute_ptr m_EStringToStringMapEntry__value;
 	::ecore::EReference_ptr m_EGenericType__eUpperBound;
 	::ecore::EReference_ptr m_EGenericType__eTypeArguments;
 	::ecore::EReference_ptr m_EGenericType__eRawType;
 	::ecore::EReference_ptr m_EGenericType__eLowerBound;
 	::ecore::EReference_ptr m_EGenericType__eTypeParameter;
 	::ecore::EReference_ptr m_EGenericType__eClassifier;
 	::ecore::EReference_ptr m_ETypeParameter__eBounds;
};

} // ecore


#endif // EMF_CPP_ECORE_PACKAGE_HPP
