
#ifndef EMF_CPP_KDM_CODE_INC_HPP
#define EMF_CPP_KDM_CODE_INC_HPP

#include <kdm/code/fwd.hpp>

#include <kdm/core/fwd.hpp>
#include <kdm/kdm/fwd.hpp>
#include <kdm/source/fwd.hpp>
#include <kdm/action/fwd.hpp>


#include <kdm/code/AbstractCodeElement.hpp>
#include <kdm/code/CodeItem.hpp>
#include <kdm/code/ComputationalObject.hpp>
#include <kdm/code/ControlElement.hpp>
#include <kdm/code/MethodUnit.hpp>
#include <kdm/code/Module.hpp>
#include <kdm/code/CodeAssembly.hpp>
#include <kdm/code/CallableUnit.hpp>
#include <kdm/code/Datatype.hpp>
#include <kdm/code/TemplateUnit.hpp>
#include <kdm/code/TemplateParameter.hpp>
#include <kdm/code/AbstractCodeRelationship.hpp>
#include <kdm/code/InstanceOf.hpp>
#include <kdm/code/CompilationUnit.hpp>
#include <kdm/code/CodeModel.hpp>
#include <kdm/code/DerivedType.hpp>
#include <kdm/code/ArrayType.hpp>
#include <kdm/code/PrimitiveType.hpp>
#include <kdm/code/BooleanType.hpp>
#include <kdm/code/CharType.hpp>
#include <kdm/code/ClassUnit.hpp>
#include <kdm/code/CompositeType.hpp>
#include <kdm/code/RecordType.hpp>
#include <kdm/code/EnumeratedType.hpp>
#include <kdm/code/Extends.hpp>
#include <kdm/code/ScaledType.hpp>
#include <kdm/code/FloatType.hpp>
#include <kdm/code/HasType.hpp>
#include <kdm/code/ImplementationOf.hpp>
#include <kdm/code/Implements.hpp>
#include <kdm/code/IntegerType.hpp>
#include <kdm/code/InterfaceUnit.hpp>
#include <kdm/code/PointerType.hpp>
#include <kdm/code/DefinedType.hpp>
#include <kdm/code/TypeUnit.hpp>
#include <kdm/code/RangeType.hpp>
#include <kdm/code/Signature.hpp>
#include <kdm/code/DataElement.hpp>
#include <kdm/code/StringType.hpp>
#include <kdm/code/ChoiceType.hpp>
#include <kdm/code/NamespaceUnit.hpp>
#include <kdm/code/VisibleIn.hpp>
#include <kdm/code/CommentUnit.hpp>
#include <kdm/code/SharedUnit.hpp>
#include <kdm/code/DecimalType.hpp>
#include <kdm/code/DateType.hpp>
#include <kdm/code/TimeType.hpp>
#include <kdm/code/VoidType.hpp>
#include <kdm/code/ValueElement.hpp>
#include <kdm/code/Value.hpp>
#include <kdm/code/ValueList.hpp>
#include <kdm/code/StorableUnit.hpp>
#include <kdm/code/MemberUnit.hpp>
#include <kdm/code/ParameterUnit.hpp>
#include <kdm/code/ItemUnit.hpp>
#include <kdm/code/IndexUnit.hpp>
#include <kdm/code/SynonymType.hpp>
#include <kdm/code/SequenceType.hpp>
#include <kdm/code/BagType.hpp>
#include <kdm/code/SetType.hpp>
#include <kdm/code/CodeElement.hpp>
#include <kdm/code/CodeRelationship.hpp>
#include <kdm/code/LanguageUnit.hpp>
#include <kdm/code/OrdinalType.hpp>
#include <kdm/code/BitstringType.hpp>
#include <kdm/code/OctetType.hpp>
#include <kdm/code/OctetstringType.hpp>
#include <kdm/code/BitType.hpp>
#include <kdm/code/Imports.hpp>
#include <kdm/code/Package.hpp>
#include <kdm/code/ParameterTo.hpp>
#include <kdm/code/TemplateType.hpp>
#include <kdm/code/PreprocessorDirective.hpp>
#include <kdm/code/MacroDirective.hpp>
#include <kdm/code/MacroUnit.hpp>
#include <kdm/code/ConditionalDirective.hpp>
#include <kdm/code/IncludeDirective.hpp>
#include <kdm/code/VariantTo.hpp>
#include <kdm/code/Expands.hpp>
#include <kdm/code/Redefines.hpp>
#include <kdm/code/GeneratedFrom.hpp>
#include <kdm/code/Includes.hpp>
#include <kdm/code/HasValue.hpp>

#include <kdm/code/CodeFactory.hpp>
#include <kdm/code/CodePackage.hpp>

#endif // EMF_CPP_KDM_CODE_INC_HPP
